export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_LOGINUSER_REQUEST = "LOAD_LOGINUSER_REQUEST";
export const LOAD_LOGINUSER_SUCCESS = "LOAD_LOGINUSER_SUCCESS";
export const LOAD_LOGINUSER_FAIL = "LOAD_LOGINUSER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const EXTRA_DETAILS = "EXTRA_DETAILS";

export const Clear_Error = "Clear_Error";
