export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SECCESS = "SEARCH_PRODUCT_SECCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";
export const RESET_SEARCH_PRODUCT = "RESET_SEARCH_PRODUCT";

// export const SINGLE_PRODUCT_DETAIL_REQUEST = "SINGLE_PRODUCT_DETAIL_REQUEST";
// export const SINGLE_PRODUCT_DETAIL_SUCCESS = "SINGLE_PRODUCT_DETAIL_SUCCESS";
// export const SINGLE_PRODUCT_DETAIL_FAIL = "SINGLE_PRODUCT_DETAIL_FAIL";

export const SINGLE_PRODUCT_UPDATE_REQUEST = "SINGLE_PRODUCT_UPDATE_REQUEST";
export const SINGLE_PRODUCT_UPDATE_SUCCESS = "SINGLE_PRODUCT_UPDATE_SUCCESS";
export const SINGLE_PRODUCT_UPDATE_FAIL = "SINGLE_PRODUCT_UPDATE_FAIL";
export const RESET_PRODUCT_UPDATE = "RESET_PRODUCT_UPDATE";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const RESET_DELETED_PRODUCT = "RESET_DELETED_PRODUCT";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";
export const RESET_NEW_PRODUCT = "RESET_NEW_PRODUCT";

export const CLEAR_SEARCH_ERROR = "CLEAR_SEARCH_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";
